# Generated by Django 4.0.2 on 2022-02-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('origin_of_company', models.TextField()),
                ('assurance', models.CharField(max_length=255)),
                ('necessary', models.TextField()),
                ('appointment_with', models.TextField()),
                ('arrival_time', models.TimeField(auto_now_add=True)),
                ('departure_time', models.TimeField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.TextField()),
            ],
        ),
    ]
