# Generated by Django 4.0.2 on 2022-03-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
