# Generated by Django 4.0.2 on 2022-03-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0003_datalist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_assurance', models.TextField()),
            ],
        ),
    ]
